services:
  flask:
    build: .
    container_name: flask-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - /home/ubuntu/.env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  apache:
    build: ./apache
    container_name: apache
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/httpd-vhosts-active.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - /home/ubuntu/factsorlie/.well-known:/usr/local/apache2/htdocs/.well-known
      - /home/ubuntu/factsorlie/wolfGuard:/usr/local/apache2/htdocs/wolfGuard:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/openssl.cnf:/etc/ssl/openssl.cnf:ro
    depends_on:
      - flask

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
